version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./mephisto
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/social_site
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: system
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: social_site
      MYSQL_ROOT_PASSWORD: system
    ports:
      - "3306:3306"
